ALTER SESSION SET CONTAINER=ORCLPDB1;

CREATE USER IPCLAB_DOM IDENTIFIED BY IPCLAB_DOM QUOTA UNLIMITED ON "USERS";
GRANT CONNECT, RESOURCE, CREATE SEQUENCE, CREATE SESSION, CREATE SYNONYM, CREATE TABLE, CREATE VIEW TO IPCLAB_DOM;